repositories:
  - name: jafow
    url: git+https://github.com/jafow/charts@stable/traefik?ref=master

helmDefaults:
  wait: true
  timeout: 300
  createNamespace: true

releases:
  - name: traefik
    namespace: kube-system
    chart: "../../charts/stable/traefik"
    # chart: "jafow/traefik"
    labels:
      service: traefik
      stage: dev
    values:
      - deployment:
          replicas: 1
